FROM mcr.microsoft.com/windows/servercore:ltsc2019

# Install Visual Studio Build Tools
ADD https://aka.ms/vs/16/release/vs_buildtools.exe vs_buildtools.exe
RUN vs_buildtools.exe --quiet --wait --norestart --nocache \
    --installPath C:\BuildTools \
    --add Microsoft.VisualStudio.Workload.VCTools \
    --add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 \
    --add Microsoft.VisualStudio.Component.VC.CMake.Project \
    || IF "%ERRORLEVEL%"=="3010" EXIT 0

# Install CMake
ADD https://github.com/Kitware/CMake/releases/download/v3.21.1/cmake-3.21.1-windows-x86_64.msi cmake-installer.msi
RUN msiexec.exe /i cmake-installer.msi /quiet /norestart

RUN winget install -e --id Kitware.CMake