name: ci
on:
  pull_request:
    branches:
      - main
      - dev
  push:
    tags:
      - '*'
    branches:
      - main
      - dev

jobs:
  Test:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3

      - name: Setup Cpp
        uses: aminya/setup-cpp@v1
        with:
          compiler: gcc-11
          cmake: true

      - name: Compilation
        run: |
          cmake -S . -B ./build
          cmake --build ./build ${{env.nproc}}
          
      - name: CPack
        working-directory: ./build
        run: |
          cpack -G ZIP

      - name: Publish Tagged Release
        uses: softprops/action-gh-release@v1
        if: ${{ startsWith(github.ref, 'refs/tags/')}}
        with:
          files: |
            build/*-*${{ matrix.build_type }}*-*.*
